baseURL = 'https://partagedanslemonde.org/'
languageCode = 'en-us'
title = 'Partage Dans Le Monde – Puducherry | Education, Healthcare & Community Development'
theme = 'pdlm-theme'
[params]
favicon = "/images/logo.png"
description = "Discover how Partage Dans Le Monde – Puducherry transforms lives through education, healthcare, and sustainable community programs. Join us in making a lasting impact."
keywords = "Partage Dans Le Monde Puducherry, NGO Puducherry, community development, education NGO India, healthcare support NGO, sustainable development NGO"
author = "Dhanila - TenSketch"
logo = "/images/logo.png"
og_image = "/ogimage.jpg"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Success Stories"
    url = "/success-stories/"
    weight = 2

  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 3

  [[menu.main]]
    name = "Our Work"
    url = "/our-work/"
    weight = 4
    
  [[menu.main]]
    name = "Reports"
    identifier = "reports"
    url = "#"
    weight = 5

    [[menu.main]]
      parent = "reports"
      name = "Audit Reports"
      url = "/audit-report/"
      weight = 1

    [[menu.main]]
      parent = "reports"
      name = "Annual Reports"
      url = "/annual-report/"
      weight = 2

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 6

  [[menu.main]]
    identifier = "phone"
    name = "Call"
    url = "tel:+919876543210"
    weight = 7
    pre = "<i class='fas fa-phone'></i> "

  [[menu.main]]
    identifier = "whatsapp"
    name = "WhatsApp"
    url = "https://wa.me/+919842178711"
    weight = 8
    pre = "<i class='fab fa-whatsapp'></i> "

  [[menu.main]]
    name = "Get Involved"
    url = "/volunteer/"
    weight = 9
    params = { class = "btn btn-primary text-light" }


  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Success Stories"
    url = "/success-stories/"
    weight = 2

  [[menu.footer]]
    name = "About Us"
    url = "/about-us/"
    weight = 3

  [[menu.footer]]
    name = "Our Work"
    url = "/our-work/"
    weight = 4
    
  [[menu.footer]]
    name = "Audit Reports"
    url = "/audit-report/"
    weight = 5

  [[menu.footer]]
    name = "Annual Reports"
    url = "/annual-report/"
    weight = 6

  [[menu.footer]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 7

  [[menu.footer]]
    name = "Volunteer with us"
    url = "/volunteer/"
    weight = 8